apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-pod
    spec:
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/app:0.1
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 3031
        - image: gcr.io/YOUR_PROJECT_ID/app-nginx:0.1
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: NodePort
  selector:
    app: hello-pod
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: hello-service
          servicePort: 80
